version: '3'
services:
  logstash:
    image: logstash_nginx
    build: logstash
    ports:
      - "5000:5000"
    command: bin/logstash

  webserver:
    image: nginx_custom
    container_name: nginx-with-syslog
    ports:
      - "80:80"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"
        syslog-tag: "nginx-with-syslog"
