version: '3'
services:
  logstash_docker:
    image: logstash_nginx
    container_name: logstash_nginx_parse
    ports:
      - "5000:5000"

  nginx_docker:
    image: nginx_custom
    container_name: nginx_with_syslog
    ports:
      - "80:80"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"
